// Structure UI | stru.ca | Copyright Neural Systems Inc

module Structureˉui
{
    /**
     * A mapping between the html attributes and the UI Element attributes, the code is written 
     * this way to help achieve 2 things, mapping from JSX to Html, and for Google Closure 
     * Compiler when it renames the object names.
     */
    export class Uiˉattributesˉmap
    {
        static readonly Style = 'style'
        static readonly Id = 'id'
        static readonly Class = 'class'

        static readonly Onˉabort = 'onabort'
        static readonly Onˉanimationˉcancel = 'onanimationcancel'
        static readonly Onˉanimationˉend = 'onanimationend'
        static readonly Onˉanimationˉiteration = 'onanimationiteration'
        static readonly Onˉanimationˉstart = 'onanimationstart'
        static readonly Onˉauxˉclick = 'onauxclick'
        static readonly Onˉblur = 'onblur'
        static readonly Onˉcancel = 'oncancel'
        static readonly Onˉcanˉplay = 'oncanplay'
        static readonly Onˉcanˉplayˉthrough = 'oncanplaythrough'
        static readonly Onˉchange = 'onchange'
        static readonly Onˉclick = 'onclick'
        static readonly Onˉclose = 'onclose'
        static readonly Onˉcontextˉmenu = 'oncontextmenu'
        static readonly Onˉcueˉchange = 'oncuechange'
        static readonly Onˉdblˉclick = 'ondblclick'
        static readonly Onˉdrag = 'ondrag'
        static readonly Onˉdragˉend = 'ondragend'
        static readonly Onˉdragˉenter = 'ondragenter'
        static readonly Onˉdragˉexit = 'ondragexit'
        static readonly Onˉdragˉleave = 'ondragleave'
        static readonly Onˉdragˉover = 'ondragover'
        static readonly Onˉdragˉstart = 'ondragstart'
        static readonly Onˉdrop = 'ondrop'
        static readonly Onˉdurationˉchange = 'ondurationchange'
        static readonly Onˉemptied = 'onemptied'
        static readonly Onˉended = 'onended'
        static readonly Onˉerror = 'onerror'
        static readonly Onˉfocus = 'onfocus'
        static readonly Onˉgotˉpointerˉcapture = 'ongotpointercapture'
        static readonly Onˉinput = 'oninput'
        static readonly Onˉinvalid = 'oninvalid'
        static readonly Onˉkeyˉdown = 'onkeydown'
        static readonly Onˉkeyˉpress = ''
        static readonly Onˉkeyˉup = 'onkeyup'
        static readonly Onˉload = 'onload'
        static readonly Onˉloadedˉdata = 'onloadeddata'
        static readonly Onˉloadedˉmetadata = 'onloadedmetadata'
        static readonly Onˉloadˉstart = 'onloadstart'
        static readonly Onˉlostˉpointerˉcapture = 'onlostpointercapture'
        static readonly Onˉmouseˉdown = 'onmousedown'
        static readonly Onˉmouseˉenter = 'onmouseenter'
        static readonly Onˉmouseˉleave = 'onmouseleave'
        static readonly Onˉmouseˉmove = 'onmousemove'
        static readonly Onˉmouseˉout = 'onmouseout'
        static readonly Onˉmouseˉover = 'onmouseover'
        static readonly Onˉmouseˉup = 'onmouseup'
        static readonly Onˉpause = 'onpause'
        static readonly Onˉplay = 'onplay'
        static readonly Onˉplaying = 'onplaying'
        static readonly Onˉpointerˉcancel = 'onpointercancel'
        static readonly Onˉpointerˉdown = 'onpointerdown'
        static readonly Onˉpointerˉenter = 'onpointerenter'
        static readonly Onˉpointerˉleave = 'onpointerleave'
        static readonly Onˉpointerˉmove = 'onpointermove'
        static readonly Onˉpointerˉout = 'onpointerout'
        static readonly Onˉpointerˉover = 'onpointerover'
        static readonly Onˉpointerˉup = 'onpointerup'
        static readonly Onˉprogress = 'onprogress'
        static readonly Onˉrateˉchange = 'onratechange'
        static readonly Onˉreset = 'onreset'
        static readonly Onˉresize = 'onresize'
        static readonly Onˉscroll = 'onscroll'
        static readonly Onˉsecurityˉpolicyˉviolation = 'onsecuritypolicyviolation'
        static readonly Onˉseeked = 'onseeked'
        static readonly Onˉseeking = 'onseeking'
        static readonly Onˉselect = 'onselect'
        static readonly Onˉselectionˉchange = 'onselectionchange'
        static readonly Onˉselectˉstart = 'onselectstart'
        static readonly Onˉstalled = 'onstalled'
        static readonly Onˉsubmit = 'onsubmit'
        static readonly Onˉsuspend = 'onsuspend'
        static readonly Onˉtimeˉupdate = 'ontimeupdate'
        static readonly Onˉtoggle = 'ontoggle'
        static readonly Onˉtouchˉcancel = 'ontouchcancel'
        static readonly Onˉtouchˉend = 'ontouchend'
        static readonly Onˉtouchˉmove = 'ontouchmove'
        static readonly Onˉtouchˉstart = 'ontouchstart'
        static readonly Onˉtransitionˉcancel = 'ontransitioncancel'
        static readonly Onˉtransitionˉend = 'ontransitionend'
        static readonly Onˉtransitionˉrun = 'ontransitionrun'
        static readonly Onˉtransitionˉstart = 'ontransitionstart'
        static readonly Onˉvolumeˉchange = 'onvolumechange'
        static readonly Onˉwaiting = 'onwaiting'
        static readonly Onˉwheel = 'onwheel'
    }
}